spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventpulse
    username: root
    password: Aashish@2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true